import type { CSSProperties } from "react";
import { unstyledButton } from "@/lib/interactive";

/** Co-located styles for the Onboarding Tour page and its parts (design: screen_tour_context.jsx). */
export const s = {
  // ---- page frame
  centered: { padding: "24px 28px" } satisfies CSSProperties,
  skeletonStack: { display: "flex", flexDirection: "column", gap: 12, padding: "24px 28px" } satisfies CSSProperties,
  errorText: { color: "var(--crit)", fontSize: 13, marginBottom: 8 } satisfies CSSProperties,
  layout: {
    display: "flex",
    gap: 28,
    padding: "24px 28px 40px",
    maxWidth: 1080,
    margin: "0 auto",
  } satisfies CSSProperties,
  main: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  banner: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    marginBottom: 16,
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    color: "var(--text-primary)",
    fontSize: 13,
  } satisfies CSSProperties,
  bannerText: { flex: 1, minWidth: 0 } satisfies CSSProperties,

  // ---- "On this page"
  navWrap: { width: 180, flexShrink: 0 } satisfies CSSProperties,
  navSticky: { position: "sticky", top: 16 } satisfies CSSProperties,
  navLabel: {
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
    margin: "0 0 10px",
  } satisfies CSSProperties,
  navList: { listStyle: "none", margin: 0, padding: 0 } satisfies CSSProperties,
  navItem: (active: boolean): CSSProperties => ({
    ...unstyledButton,
    display: "block",
    width: "100%",
    fontSize: 12.5,
    color: active ? "var(--text-primary)" : "var(--text-secondary)",
    fontWeight: active ? 600 : 500,
    padding: "5px 0 5px 11px",
    borderLeft: `2px solid ${active ? "var(--accent)" : "transparent"}`,
    transition: "color .12s",
  }),

  // ---- header
  header: { display: "flex", alignItems: "flex-start", gap: 12, marginBottom: 20, flexWrap: "wrap" } satisfies CSSProperties,
  headerText: { flex: 1, minWidth: 240 } satisfies CSSProperties,
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em", margin: 0 } satisfies CSSProperties,
  repo: { color: "var(--accent-text)" } satisfies CSSProperties,
  subtitle: { fontSize: 12.5, color: "var(--text-muted)", margin: "5px 0 0" } satisfies CSSProperties,
  notes: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 8, marginTop: 8 } satisfies CSSProperties,
  note: { fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  headerActions: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  confirmation: { fontSize: 12, color: "var(--ok)", minWidth: 56 } satisfies CSSProperties,
  confirmationError: { fontSize: 12, color: "var(--crit)" } satisfies CSSProperties,

  // ---- cards
  card: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    marginBottom: 14,
    overflow: "hidden",
    scrollMarginTop: 16,
  } satisfies CSSProperties,
  cardHeader: {
    ...unstyledButton,
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "13px 16px",
  } satisfies CSSProperties,
  cardIcon: {
    width: 28,
    height: 28,
    borderRadius: 7,
    background: "var(--accent-bg)",
    color: "var(--accent)",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  } satisfies CSSProperties,
  cardTitle: { fontSize: 14.5, fontWeight: 600, flex: 1, margin: 0 } satisfies CSSProperties,
  chevron: (open: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    transform: open ? "rotate(180deg)" : "none",
    transition: "transform .15s",
  }),
  cardBody: { padding: "0 16px 16px" } satisfies CSSProperties,
  cardEmpty: { fontSize: 13, color: "var(--text-muted)", margin: 0 } satisfies CSSProperties,

  // ---- section bodies
  overviewText: { fontSize: 13.5, lineHeight: 1.6, color: "var(--text-secondary)" } satisfies CSSProperties,
  diagram: { marginTop: 12 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8, marginTop: 4, padding: 0, listStyle: "none", marginBottom: 0 } satisfies CSSProperties,
  fileRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 11px",
    borderRadius: 7,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  fileIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  path: { fontSize: 13, color: "var(--text-secondary)", wordBreak: "break-all" } satisfies CSSProperties,
  pathLink: { fontSize: 13, wordBreak: "break-all" } satisfies CSSProperties,
  openLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 9px",
    fontSize: 12.5,
    fontWeight: 500,
    lineHeight: 1.2,
    borderRadius: 6,
    border: "1px solid var(--border)",
    color: "var(--text-secondary)",
    textDecoration: "none",
    flexShrink: 0,
  } satisfies CSSProperties,
  note2: { fontSize: 12, color: "var(--text-secondary)", flex: 1, minWidth: 0 } satisfies CSSProperties,
  stepRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "9px 12px",
    borderRadius: 7,
    background: "var(--code-bg)",
    border: "1px solid var(--border)",
  } satisfies CSSProperties,
  stepNumber: { fontSize: 11, color: "var(--text-muted)", width: 14, marginTop: 2 } satisfies CSSProperties,
  stepBody: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  command: { fontSize: 12, color: "var(--text-primary)", whiteSpace: "pre-wrap", wordBreak: "break-all" } satisfies CSSProperties,
  source: { fontSize: 11, color: "var(--text-muted)", marginTop: 3 } satisfies CSSProperties,
  stepCopy: { display: "flex", alignItems: "center", gap: 6, flexShrink: 0 } satisfies CSSProperties,
  stepConfirm: { fontSize: 11.5, color: "var(--ok)" } satisfies CSSProperties,
  stepConfirmError: { fontSize: 11.5, color: "var(--crit)" } satisfies CSSProperties,
  warning: { fontSize: 12, color: "var(--warn)", margin: "12px 0 0" } satisfies CSSProperties,
  readingRow: { display: "flex", gap: 11, alignItems: "flex-start" } satisfies CSSProperties,
  readingNumber: {
    width: 20,
    height: 20,
    borderRadius: 99,
    background: "var(--accent-bg)",
    color: "var(--accent)",
    fontSize: 11,
    fontWeight: 700,
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    marginTop: 1,
  } satisfies CSSProperties,
  why: { fontSize: 12.5, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  tasks: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 10, marginTop: 4 } satisfies CSSProperties,
  task: {
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    listStyle: "none",
  } satisfies CSSProperties,
  taskTitle: { fontSize: 13, fontWeight: 600, lineHeight: 1.35 } satisfies CSSProperties,
  taskScope: { fontSize: 11, color: "var(--text-muted)", margin: "7px 0", wordBreak: "break-all" } satisfies CSSProperties,
  complexity: (level: "low" | "medium" | "high"): CSSProperties => ({
    color: level === "low" ? "var(--ok)" : level === "medium" ? "var(--warn)" : "var(--crit)",
    border: "1px solid var(--border-strong)",
  }),

  // ---- footer
  footer: { fontSize: 11.5, color: "var(--text-muted)", margin: "4px 0 0" } satisfies CSSProperties,
} as const;
