/* /repos/:repoId/onboarding — the repository's onboarding tour: five cards (architecture overview, critical
   paths, how to run locally, guided reading path, first tasks) generated by one model request in the
   background. Every state is derived from the query cache during render: the stored tour, the generation
   state (polled while it runs) and the repository's indexed commit. Nothing about the tour is copied to state. */
"use client";

import React from "react";
import { useTranslations } from "next-intl";
import { Button, EmptyState, ErrorState, Skeleton } from "@devdigest/ui";
import type { TourSectionKind } from "@devdigest/shared";
import { usePageCrumb } from "@/components/app-shell";
import { RepoNotFound } from "@/components/repo-not-found";
import { ApiError } from "@/lib/api";
import { useGenerateOnboardingTour, useOnboardingTour } from "@/lib/hooks/onboarding-tour";
import { useRepoIntelStatus } from "@/lib/hooks/repo-intel";
import { useActiveRepo, useRepoNotFound } from "@/lib/repo-context";
import { GENERATION_IN_PROGRESS, SECTION_ICON, SKELETON_ROWS, TOUR_KINDS } from "./constants";
import { isSectionEmpty, isTourStale } from "./helpers";
import { useActiveSection } from "./hooks/useActiveSection";
import { TourCard } from "./_components/TourCard";
import { TourFooter } from "./_components/TourFooter";
import { TourHeader } from "./_components/TourHeader";
import { TourNav } from "./_components/TourNav";
import { TourSectionBody } from "./_components/TourSections";
import { s } from "./styles";

export function TourView({ repoId }: { repoId: string }) {
  const t = useTranslations("onboarding");
  const { activeRepo } = useActiveRepo();
  const repoNotFound = useRepoNotFound(repoId);
  const read = useOnboardingTour(repoId);
  const generate = useGenerateOnboardingTour(repoId);
  const intel = useRepoIntelStatus(repoId);
  // Cards the user collapsed this visit; nothing is persisted, so every visit starts with all five open.
  const [collapsed, setCollapsed] = React.useState<ReadonlySet<TourSectionKind>>(() => new Set());
  const wrapRef = React.useRef<HTMLDivElement>(null);

  const tour = read.data?.tour ?? null;
  const generation = read.data?.generation;
  const running = generation?.status === "running";
  const notCloned = activeRepo?.clone_path === null;
  const showingTour = !repoNotFound && !notCloned && !!activeRepo && !!tour;
  const { active, jumpTo } = useActiveSection(wrapRef, TOUR_KINDS, showingTour);

  usePageCrumb([{ label: activeRepo?.full_name ?? t("page.repoFallback"), mono: true }, { label: t("page.crumb") }]);

  if (repoNotFound) return <RepoNotFound />;

  if (notCloned) {
    return (
      <div style={s.centered}>
        <EmptyState icon="Boxes" title={t("notCloned.title")} body={t("notCloned.body")} />
      </div>
    );
  }

  if (read.isPending || !activeRepo) {
    return (
      <div style={s.skeletonStack} role="status" aria-label={t("page.loading")}>
        {Array.from({ length: SKELETON_ROWS }).map((_, i) => (
          <Skeleton key={i} height={64} />
        ))}
      </div>
    );
  }

  if (read.isError && !read.data) {
    return (
      <div style={s.centered}>
        <ErrorState title={t("page.loadError")} onRetry={() => void read.refetch()} />
      </div>
    );
  }

  const start = () => generate.mutate();
  // Why the last generation (or the request to start one) did not work, if it did not.
  const startFailure =
    generate.error && !(generate.error instanceof ApiError && generate.error.code === GENERATION_IN_PROGRESS)
      ? generate.error.message
      : null;
  const failure = generation?.status === "failed" ? generation.error || t("error.unknown") : startFailure;

  if (!tour && running) {
    return (
      <div style={s.centered} role="status">
        <EmptyState icon="Boxes" title={t("generating.title")} />
      </div>
    );
  }

  if (!tour) {
    return (
      <div style={s.centered}>
        <EmptyState
          icon="Boxes"
          title={t("empty.title")}
          body={
            <>
              {t("empty.body")}
              {failure && (
                <p role="alert" style={{ ...s.errorText, marginTop: 12, marginBottom: 0 }}>
                  {failure}
                </p>
              )}
            </>
          }
          cta={t("empty.cta")}
          onCta={start}
          ctaLoading={generate.isPending}
        />
      </div>
    );
  }

  const toggle = (kind: TourSectionKind) =>
    setCollapsed((prev) => {
      const next = new Set(prev);
      if (!next.delete(kind)) next.add(kind);
      return next;
    });
  // Jumping to a collapsed card opens it first; the card's top does not move, so scrolling can follow at once.
  const activate = (kind: TourSectionKind) => {
    setCollapsed((prev) => {
      if (!prev.has(kind)) return prev;
      const next = new Set(prev);
      next.delete(kind);
      return next;
    });
    jumpTo(kind);
  };

  return (
    <div ref={wrapRef} style={s.layout}>
      <TourNav active={active} onActivate={activate} />
      <div style={s.main}>
        {failure && (
          <div role="alert" style={s.banner}>
            <span style={s.bannerText}>{failure}</span>
            <Button kind="secondary" size="sm" icon="RefreshCw" disabled={running || generate.isPending} onClick={start}>
              {t("error.retry")}
            </Button>
          </div>
        )}
        <TourHeader
          tour={tour}
          repoName={activeRepo.name}
          repoFullName={activeRepo.full_name}
          stale={isTourStale(intel.data?.lastIndexedSha, tour.commit_sha)}
          regenerating={running || generate.isPending}
          onRegenerate={start}
        />
        {tour.sections.map((section) => (
          <TourCard
            key={section.kind}
            kind={section.kind}
            icon={SECTION_ICON[section.kind]}
            title={t(`sections.${section.kind}`)}
            open={!collapsed.has(section.kind)}
            onToggle={() => toggle(section.kind)}
            empty={isSectionEmpty(section)}
          >
            <TourSectionBody section={section} repoName={activeRepo.full_name} commit={tour.commit_sha} />
          </TourCard>
        ))}
        <TourFooter tour={tour} />
      </div>
    </div>
  );
}
