import type { CSSProperties } from "react";

/** Co-located styles for ConventionCard. */
export const s = {
  card: (accepted: boolean): CSSProperties => ({
    border: "1px solid " + (accepted ? "var(--ok)" : "var(--border)"),
    borderRadius: 9,
    background: "var(--bg-elevated)",
    padding: 16,
    marginBottom: 12,
  }),
  topRow: { display: "flex", alignItems: "center", gap: 10, marginBottom: 10 } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  rule: { fontSize: 14, fontWeight: 600, lineHeight: 1.45, margin: 0 } satisfies CSSProperties,
  editBox: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  editError: { fontSize: 12, color: "var(--crit)" } satisfies CSSProperties,
  editActions: { display: "flex", gap: 8 } satisfies CSSProperties,
  evidence: {
    marginTop: 10,
    borderRadius: 7,
    border: "1px solid var(--border)",
    overflow: "hidden",
  } satisfies CSSProperties,
  evidenceHead: {
    display: "flex",
    alignItems: "center",
    padding: "5px 10px",
    background: "var(--bg-surface)",
    borderBottom: "1px solid var(--border)",
    fontSize: 12,
    minWidth: 0,
  } satisfies CSSProperties,
  link: {
    color: "var(--accent-text)",
    textDecoration: "none",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  plainLocation: { color: "var(--text-secondary)" } satisfies CSSProperties,
  code: {
    margin: 0,
    padding: "8px 0",
    fontSize: 11.5,
    lineHeight: 1.55,
    color: "var(--text-primary)",
    background: "var(--code-bg)",
    overflow: "auto",
  } satisfies CSSProperties,
  codeLine: { display: "flex", padding: "0 12px" } satisfies CSSProperties,
  lineNo: {
    flexShrink: 0,
    width: 36,
    paddingRight: 12,
    textAlign: "right",
    color: "var(--text-muted)",
    userSelect: "none",
  } satisfies CSSProperties,
  lineText: { whiteSpace: "pre" } satisfies CSSProperties,
  confidenceRow: { display: "flex", alignItems: "center", gap: 10, marginTop: 10 } satisfies CSSProperties,
  confidenceLabel: { fontSize: 11, color: "var(--text-muted)" } satisfies CSSProperties,
  confidenceBar: { width: 90 } satisfies CSSProperties,
  confidencePct: { fontSize: 11, color: "var(--text-secondary)" } satisfies CSSProperties,
  actions: { display: "flex", alignItems: "center", gap: 8, marginTop: 14, flexWrap: "wrap" } satisfies CSSProperties,
} as const;
