/**
 * Review module constants.
 */

/**
 * Studio review strategy. 'single-pass' = send the WHOLE diff in ONE LLM call.
 * We deliberately do NOT use 'auto'/map-reduce by default: map-reduce makes one
 * call PER FILE, which is slow and fragile (any single file's transient 5xx
 * fails the entire run) and unnecessary — the whole diff already fits the
 * model's context.
 */
export const REVIEW_STRATEGY = 'single-pass' as const;

/**
 * Paths dropped from the diff BEFORE it is handed to a review agent.
 *
 * These are generated or fixture files: reviewing them burns context and, worse,
 * feeds the model fake file paths. The unpacked design export is ~30 JSX files of
 * MOCK data (a fictional PR "Add rate limiting…" whose mock objects cite
 * `src/middleware/ratelimit.ts`); a reviewer read those as real code and reported a
 * finding about a file that does not exist, which citation grounding then dropped —
 * a full-price run that persisted nothing.
 *
 * Pattern forms (see `diff-filter.ts`): `dir` + slash + `**` prefix, `**` + slash + `name`
 * basename (name may itself have wildcards or more slashes), `*.ext`-style wildcard, or
 * an exact path. Keep the list small and only for files nobody authors by hand.
 */
export const REVIEW_EXCLUDED_PATHS: string[] = [
  'client/docs/design/**', // unpacked Claude Design export — mock data, not code
  'server/src/db/migrations/**', // generated by `pnpm db:generate`, never hand-edited
  'server/src/experiments/fixtures/**', // control-PR diffs that cite files of a fictional repo
  '**/pnpm-lock.yaml', // one per package — this repo is not a pnpm workspace
  '**/package-lock.json',
  '*.lock',

  // Dart/Flutter codegen (`build_runner`) — never authored by hand, reviewing it burns
  // context and risks findings against generated code (`INSIGHTS.md` rationale above).
  '*.g.dart',
  '*.freezed.dart',
  '*.gr.dart', // auto_route
  '*.mocks.dart', // mockito/build_runner
  '*.gen.dart',
  '*.config.dart', // injectable
  '*.pb.dart', // protobuf
  '*.pbenum.dart',
  '*.pbjson.dart',
  '*.pbserver.dart',
  '**/generated/**', // intl_utils and other codegen output directories
  '**/l10n/app_localizations*.dart', // flutter gen-l10n output
  '**/GeneratedPluginRegistrant.*', // Flutter tool output (Android/iOS/desktop)
  '**/generated_plugin_registrant.*',
  '**/Flutter/ephemeral/**', // Flutter tool scratch dir (iOS/macOS runner)
  '**/Generated.xcconfig',
];
