// Flat config, ESLint 9. Not type-aware on purpose: `pnpm typecheck` runs tsc over the
// same files in the same CI lane. What this config adds is what tsc cannot see —
// unused code, `any`, and the layering rules from server/AGENTS.md.
import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      // Runtime git checkouts — a full copy of this repo lives in here.
      "clones/**",
      // Generated by `pnpm db:generate`.
      "src/db/migrations/**",
      // Vendored: the canonical Zod contracts, shared verbatim with reviewer-core.
      "src/vendor/**",
    ],
  },
  js.configs.recommended,
  tseslint.configs.recommended,
  {
    rules: {
      // tsc already resolves every identifier, including Node globals.
      "no-undef": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/consistent-type-imports": ["error", { fixStyle: "inline-type-imports" }],
    },
  },
  // No architectural `no-restricted-imports` here yet: three starter routes
  // (pulls, settings, workspace) query drizzle directly, so the rule would fail on
  // code this lesson does not own. Add it when those modules grow a repository.
);
