import type { CSSProperties } from "react";

export const s = {
  banner: {
    display: "flex",
    gap: 16,
    alignItems: "flex-start",
    padding: 16,
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  iconBox: (bg: string, color: string): CSSProperties => ({
    width: 40,
    height: 40,
    borderRadius: 9,
    display: "grid",
    placeItems: "center",
    background: bg,
    color,
    flexShrink: 0,
  }),
  main: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  titleRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    marginBottom: 6,
  } satisfies CSSProperties,
  verdictLabel: (color: string): CSSProperties => ({ fontSize: 16, fontWeight: 700, color }),
  hint: {
    display: "inline-flex",
    cursor: "help",
    color: "var(--text-muted)",
    background: "none",
    border: "none",
    padding: 0,
  } satisfies CSSProperties,
  summary: {
    margin: 0,
    fontSize: 13.5,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  summarySkeleton: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  refresh: (disabled: boolean): CSSProperties => ({
    width: 30,
    height: 30,
    display: "inline-grid",
    placeItems: "center",
    flexShrink: 0,
    borderRadius: 6,
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: disabled ? "not-allowed" : "pointer",
    opacity: disabled ? 0.5 : 1,
  }),
  scoreCol: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    flexShrink: 0,
  } satisfies CSSProperties,
  scoreLabel: {
    fontSize: 10.5,
    color: "var(--text-muted)",
    letterSpacing: "0.04em",
  } satisfies CSSProperties,
  note: {
    fontSize: 12,
    color: "var(--text-muted)",
    margin: "8px 0 0",
  } satisfies CSSProperties,
  notice: {
    fontSize: 12,
    color: "var(--warn)",
    lineHeight: 1.5,
    margin: "8px 0 0",
  } satisfies CSSProperties,
  inlineError: {
    fontSize: 12.5,
    color: "var(--crit)",
    lineHeight: 1.5,
    margin: "8px 0 0",
  } satisfies CSSProperties,
  link: { color: "var(--accent-text)", textDecoration: "underline" } satisfies CSSProperties,
  footer: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    margin: "8px 0 0",
  } satisfies CSSProperties,
  empty: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    minHeight: 200,
    display: "grid",
    placeItems: "center",
    padding: 24,
  } satisfies CSSProperties,
  emptyInner: {
    textAlign: "center",
    maxWidth: 340,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 12,
  } satisfies CSSProperties,
  emptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    background: "var(--bg-hover)",
    display: "grid",
    placeItems: "center",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  emptyTitle: { fontSize: 15, fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  emptyBody: {
    margin: 0,
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  emptySkeleton: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    alignItems: "center",
  } satisfies CSSProperties,
  errorCard: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
} as const;
