import type { CSSProperties } from "react";
import { BODY_HEIGHT } from "./constants";

/** Co-located styles for ConfigTab (screenshot "Config" of the design). */
export const s = {
  tab: { flex: 1, minHeight: 0, display: "flex", flexDirection: "column" } satisfies CSSProperties,
  scroll: { flex: 1, minHeight: 0, overflow: "auto", padding: "22px 28px 24px" } satisfies CSSProperties,
  headRow: { display: "flex", alignItems: "center", gap: 10, marginBottom: 20 } satisfies CSSProperties,
  h3: { fontSize: 15, fontWeight: 600, margin: 0 } satisfies CSSProperties,
  enabled: {
    marginLeft: "auto",
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  notice: {
    display: "flex",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
    fontSize: 13,
    lineHeight: 1.45,
    marginBottom: 20,
  } satisfies CSSProperties,
  noticeIcon: { color: "var(--warn)", flexShrink: 0, marginTop: 1 } satisfies CSSProperties,
  field: { display: "flex", flexDirection: "column", gap: 8, marginBottom: 20 } satisfies CSSProperties,
  label: { fontSize: 13, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  required: { color: "var(--crit)", marginLeft: 4 } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.45 } satisfies CSSProperties,
  presetBar: { display: "flex", gap: 6, flexWrap: "wrap", marginTop: 4 } satisfies CSSProperties,
  box: {
    height: BODY_HEIGHT,
    display: "flex",
    flexDirection: "column",
    borderRadius: 8,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-surface)",
    overflow: "hidden",
  } satisfies CSSProperties,
  fileBar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "9px 14px",
    borderBottom: "1px solid var(--border)",
    flexShrink: 0,
  } satisfies CSSProperties,
  fileIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  fileName: {
    fontSize: 12.5,
    fontWeight: 600,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  tokens: { marginLeft: "auto", fontSize: 12, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  bodyHint: { fontSize: 11.5, color: "var(--text-muted)" } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 28px",
    borderTop: "1px solid var(--border)",
    background: "var(--bg-primary)",
    flexShrink: 0,
  } satisfies CSSProperties,
  message: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  invalid: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
