import type { CSSProperties } from "react";

/** Co-located styles for SkillCard (a tile of the skills grid). */
export const s = {
  item: { display: "flex", minWidth: 0 } satisfies CSSProperties,
  card: (active: boolean, enabled: boolean): CSSProperties => ({
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    padding: 14,
    borderRadius: 10,
    cursor: "pointer",
    border: "1px solid " + (active ? "var(--border-strong)" : "var(--border)"),
    background: active ? "var(--bg-hover)" : "var(--bg-elevated)",
    opacity: enabled ? 1 : 0.55,
  }),
  headerRow: { display: "flex", alignItems: "center", gap: 9 } satisfies CSSProperties,
  iconBox: (color: string): CSSProperties => ({
    width: 26,
    height: 26,
    borderRadius: 7,
    background: color + "1a",
    color,
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  }),
  name: {
    fontSize: 12.5,
    fontWeight: 600,
    flex: 1,
    minWidth: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  toggleLabel: { display: "inline-flex", alignItems: "center" } satisfies CSSProperties,
  description: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    marginTop: 4,
    lineHeight: 1.4,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  } satisfies CSSProperties,
  metaRow: { display: "flex", gap: 8, margin: "8px 0 12px", alignItems: "center" } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: "auto",
    paddingTop: 10,
    borderTop: "1px solid var(--border)",
    fontSize: 11.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  version: { fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  footerEnd: { marginLeft: "auto" } satisfies CSSProperties,
  source: {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    fontSize: 10.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  appliesTo: {
    fontSize: 10.5,
    color: "var(--text-muted)",
    background: "var(--bg-hover)",
    padding: "1px 6px",
    borderRadius: 4,
  } satisfies CSSProperties,
} as const;
