#!/usr/bin/env node
// Unpacks a Claude Design "standalone" HTML export into readable design sources.
//
//   node scripts/unpack-design.mjs <export.html> [outDir]   (outDir defaults to client/docs/design)
//
// The export is a self-extracting bundle: three JSON <script> blocks —
// `__bundler/manifest` (uuid → base64, optionally gzipped file), `__bundler/template`
// (the page: token CSS + the canvas layout JSX) and `__bundler/ext_resources`.
// We keep only the design itself: screen/component JSX, tokens, canvas layout, and a
// generated artboard index. React/ReactDOM/Babel (text/javascript), fonts and the
// canvas tooling (DesignCanvas, tweaks panel) are dropped. The export is copied next to
// the sources so the design can still be opened in a browser.
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { fileURLToPath } from 'node:url';

const [input, outArg] = process.argv.slice(2);
if (!input) {
  console.error('usage: node scripts/unpack-design.mjs <export.html> [outDir]');
  process.exit(1);
}
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.resolve(outArg ?? path.join(root, 'client/docs/design'));
const srcDir = path.join(outDir, 'src');
const TOOLING = new Set(['DesignCanvas.jsx', 'tweaks-panel.jsx']);
const GENERATED = 'Generated by scripts/unpack-design.mjs from a Claude Design export — do not hand-edit.';

const html = fs.readFileSync(input, 'utf8');
const block = (type) => {
  const m = html.match(new RegExp(`<script type="__bundler/${type}">([\\s\\S]*?)</script>`));
  if (!m) throw new Error(`not a Claude Design standalone export: missing __bundler/${type}`);
  return JSON.parse(m[1]);
};
const manifest = block('manifest');
const template = block('template');

// ---- design sources -------------------------------------------------------
fs.rmSync(srcDir, { recursive: true, force: true });
fs.mkdirSync(srcDir, { recursive: true });

const sources = []; // { file, desc, exports }
for (const entry of Object.values(manifest)) {
  if (!['application/javascript', 'text/jsx'].includes(entry.mime)) continue; // libs, fonts
  let bytes = Buffer.from(entry.data, 'base64');
  if (entry.compressed) bytes = zlib.gunzipSync(bytes);
  const code = bytes.toString('utf8');
  const header = code.slice(0, 400).match(/([\w-]+\.jsx)\s*(?:—\s*([^*\n]+))?/);
  if (!header) throw new Error(`cannot name design file starting with: ${code.slice(0, 80)}`);
  const [, file, desc = ''] = header;
  if (TOOLING.has(file)) continue;
  fs.writeFileSync(path.join(srcDir, file), code);
  const exports = [...code.matchAll(/Object\.assign\(window,\s*\{([^}]*)\}/g)]
    .flatMap((m) => m[1].split(',').map((s) => s.trim().split(':')[0].trim()))
    .concat([...code.matchAll(/window\.([A-Z]\w*)\s*=/g)].map((m) => m[1]))
    .filter(Boolean);
  sources.push({ file, desc: desc.trim(), exports });
}
sources.sort((a, b) => a.file.localeCompare(b.file));

// ---- tokens + canvas layout from the template -----------------------------
const tokens = [...template.matchAll(/<style>([\s\S]*?)<\/style>/g)]
  .map((m) => m[1])
  .find((css) => css.includes('--bg-primary'));
fs.writeFileSync(path.join(srcDir, 'tokens.css'), `/* ${GENERATED} */\n${tokens.trim()}\n`);

const canvas = template.match(/<script type="text\/babel">([\s\S]*?)<\/script>/)[1];
fs.writeFileSync(path.join(srcDir, 'canvas.jsx'), `/* ${GENERATED} */\n${canvas.trim()}\n`);

// ---- artboard index -------------------------------------------------------
const definedIn = new Map(sources.flatMap((s) => s.exports.map((name) => [name, s.file])));
const attr = (tag, name) => tag.match(new RegExp(`${name}=(?:"([^"]*)"|\\{([^}]*)\\})`))?.slice(1).find((v) => v !== undefined) ?? '';

const lines = [`# Design artboards`, '', `> ${GENERATED}`];
const tags = canvas.matchAll(/<(DCSection|DCArtboard|window\.\w+)\b[^>]*>/g);
let pending = null; // artboard waiting for its first rendered component
for (const [tag, kind] of tags) {
  if (kind === 'DCSection') {
    lines.push('', `## ${attr(tag, 'title')} \`#${attr(tag, 'id')}\``, '', `${attr(tag, 'subtitle')}`, '');
    lines.push('| Artboard | Label | Size | Renders | Source |', '|---|---|---|---|---|');
  } else if (kind === 'DCArtboard') {
    pending = { id: attr(tag, 'id'), label: attr(tag, 'label'), size: `${attr(tag, 'width')}×${attr(tag, 'height')}` };
  } else if (pending) {
    const name = kind.slice('window.'.length);
    const props = tag.slice(1 + kind.length).replace(/\/?>$/, '').trim();
    const rendered = `\`${name}${props ? ' ' + props : ''}\``.replaceAll('|', '\\|');
    const source = definedIn.has(name) ? `\`src/${definedIn.get(name)}\`` : '`src/canvas.jsx`';
    lines.push(`| \`${pending.id}\` | ${pending.label} | ${pending.size} | ${rendered} | ${source} |`);
    pending = null;
  }
}
lines.push('', '## Source files', '', '| File | Contents |', '|---|---|');
for (const s of sources) lines.push(`| \`src/${s.file}\` | ${s.desc} |`);
lines.push('| `src/tokens.css` | Colour/density tokens and base styles (dark + light) |');
lines.push('| `src/canvas.jsx` | Canvas layout: sections, artboards and the props each screen is rendered with |');
fs.writeFileSync(path.join(outDir, 'artboards.md'), lines.join('\n') + '\n');

// ---- viewable copy of the export ------------------------------------------
const viewable = path.join(outDir, 'design.html');
if (path.resolve(input) !== viewable) fs.copyFileSync(input, viewable);

console.log(`unpacked ${sources.length} design files → ${path.relative(root, outDir)}`);
