import type { CSSProperties } from "react";

export const s = {
  meta: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 12,
    margin: 0,
    padding: 14,
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  metaLabel: {
    fontSize: 10.5,
    fontWeight: 600,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 4,
  } satisfies CSSProperties,
  metaValue: { margin: 0, fontSize: 13, color: "var(--text-primary)", display: "flex", alignItems: "center", gap: 6 } satisfies CSSProperties,
  bodyTitle: {
    fontSize: 10.5,
    fontWeight: 600,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "22px 0 8px",
  } satisfies CSSProperties,
  body: {
    padding: 16,
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    fontSize: 13.5,
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  empty: { color: "var(--text-muted)", fontSize: 13 } satisfies CSSProperties,
  footer: { display: "flex", justifyContent: "flex-end" } satisfies CSSProperties,
  open: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 13px",
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 500,
    background: "var(--accent)",
    border: "1px solid var(--accent)",
    color: "#fff",
    textDecoration: "none",
  } satisfies CSSProperties,
} as const;
